# Generated by Django 6.0.3 on 2026-03-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_userregister_delete_register_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='name',
            new_name='username',
        ),
    ]
