# Generated by Django 6.0.3 on 2026-04-04 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_name_profile_username_and_more'),
        ('notes', '0002_notes_profile_alter_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.profile'),
            preserve_default=False,
        ),
    ]
