# Generated by Django 6.0.3 on 2026-04-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
        ('notes', '0004_notes_comments_count_notes_likes_count_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user', 'note')},
        ),
    ]
