# Generated by Django 6.0.3 on 2026-04-08 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
        ('notes', '0005_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_like', to='notes.notes'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_notification', to='notes.notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='accounts.userregister')),
            ],
        ),
    ]
