# Generated by Django 6.0.3 on 2026-04-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_likes_note_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='receiver_id',
            field=models.IntegerField(null=True),
        ),
    ]
