# Generated by Django 6.0.3 on 2026-04-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_likes_receiver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='rec_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='rec_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
