# Generated by Django 6.0.3 on 2026-04-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_likes_rec_title_notification_rec_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='rec_title',
            new_name='note_title',
        ),
    ]
