# Generated by Django 6.0.3 on 2026-04-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_rename_rec_title_likes_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='rec_title',
            new_name='note_title',
        ),
    ]
