# Generated by Django 6.0.3 on 2026-04-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_notification_user_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
