# Generated by Django 6.0.3 on 2026-04-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
        ('notes', '0012_comments_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('user', 'note')},
        ),
    ]
