# Generated by Django 6.0.3 on 2026-04-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pdf_file',
            field=models.FileField(max_length=500, upload_to='pdfs/'),
        ),
    ]
